version: '3'
services:
  cors-anywhere:
    ports:
      - "4000:4000"
    container_name: cors-anywhere
    image: cors-anywhere

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: rustmq/dashboard
    environment:
     - PORT=3000
    ports: 
      - '3000:3000'

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
  web:
    env_file:
      - env.web.list
    image: rustmq/web
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - pusher

  pusher:
    env_file:
        - env.pusher.list
    image: rustmq/pusher
    ports:
    - "8080:8080"
    depends_on:
      - redis